# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-FCP
version:      1.0
version_from: FCP.pm
installdirs:  site
requires:
    AnyEvent:                      0.2
    Crypt::Rijndael:               0
    Crypt::Twofish:                0
    Digest::SHA1:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.23
