#!/usr/bin/perl

use Net::FCP qw(event=Event);

# fetch a single (small) keyand output it to stdout

my $fcp = new Net::FCP;

my ($meta, $data) = @{ $fcp->client_get ("freenet:$ARGV[0]", $ARGV[1]) };

use Data::Dumper;
print Dumper $meta;
print "=============================================================================\n";
print $data;


